name:                wya-lexer
version:             0.1.0.0
github:              devanla/wya-lexer
license:             MIT
author:              Guru Devanla
maintainer:          grdvnl@gmail.com
copyright:           2021 Guru Devanla

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/gdevanla/wya-lexer#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- array >= 0.5.4.0
- text >= 1.2.4.1
- filepath >= 1.4.2.1
- directory >= 1.3.6.0
- regex-tdfa >= 1.3.1
- utf8-string >= 1
- bytestring >= 0.10.12.0
- optparse-simple >= 0.1.1.3

#default-extensions:
        # BangPatterns
        # BinaryLiterals
        # ConstraintKinds
        # DataKinds
        # DefaultSignatures
        # DeriveDataTypeable
        # DeriveFoldable
        # DeriveFunctor
        # DeriveGeneric
        # DeriveTraversable
        # DoAndIfThenElse
        # EmptyDataDecls
        # ExistentialQuantification
        # FlexibleContexts
        # FlexibleInstances
        # FunctionalDependencies
        # GADTs
        # GeneralizedNewtypeDeriving
        # InstanceSigs
        # KindSignatures
        # LambdaCase
        # MultiParamTypeClasses
        # MultiWayIf
        # NamedFieldPuns
        # NoImplicitPrelude
        #OverloadedStrings
        # PartialTypeSignatures
        # PatternGuards
        # PolyKinds
        # RankNTypes
        # RecordWildCards
        # ScopedTypeVariables
        # StandaloneDeriving
        # TupleSections
        # TypeFamilies
        # TypeSynonymInstances
        # ViewPatterns

build-tools: alex

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  wya-lexer-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - wya-lexer
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  wya-lexer-test-1:
    main:                test_tokenizer1.hs
    source-dirs:         test
    dependencies:
    - wya-lexer
    - hspec
    - tasty
    - HUnit
    - tasty-hunit

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  wya-lexer-test-2:
    main:                test_tokenizer2.hs
    source-dirs:         test
    dependencies:
    - wya-lexer
    - hspec
    - tasty
    - HUnit
    - tasty-hunit

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N


  wya-lexer-test-3:
    main:                test_tokenizer3.hs
    source-dirs:         test
    dependencies:
    - wya-lexer
    - hspec
    - tasty
    - HUnit
    - tasty-hunit

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  wya-lexer-test-4:
    main:                test_tokenizer4.hs
    source-dirs:         test
    dependencies:
    - wya-lexer
    - hspec
    - tasty
    - HUnit
    - tasty-hunit

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  wya-lexer-test-5:
    main:                test_tokenizer5.hs
    source-dirs:         test
    dependencies:
    - wya-lexer
    - hspec
    - tasty
    - HUnit
    - tasty-hunit

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
